title: "Taylor Wang"
description: |
  B.S. Electrical Engineering, Columbia University
  Expected Graduation: May 2027
  taylw065@gmail.com
  (815) 517-5628
theme: jekyll-theme-minimal
show_downloads: false
